cluster_settings:
    backup_retention_days: 30
    conflict_resolution: manual
    connection_timeout: 10
    max_retries: 3
    sync_timeout: 60
nodes:
    prod-node-1:
        host: 216.48.191.10
        user: vunet
        key_path: ~/.ssh/id_rsa
        conf_dir: /home/vunet/load-test
        binary_dir: /home/vunet/load-test/bin
        metrics_port: 0
        description: ""
        enabled: false
